- name: setup cart server
  hosts: cart
  become: yes

  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app
  
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app
  
  - name: delete cart file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
  
  - name: download cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      path: /tmp/cart.zip
  
  - name: extract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: intall dependencies
    community.general.npm:
      path: /app
  
  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: daemon_reload, enable and start
    ansible.builtin.systemd_service:
      name: cart
      enabled: true
      state: started
      daemon_reload: true
